# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aircraft.BaseModel')),
                ('tail_number', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('manufactured_year', models.PositiveSmallIntegerField()),
                ('insurance_amount', models.FloatField(default=0)),
                ('safety_rating', models.FloatField(blank=True, null=True)),
                ('image_exterior', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('image_interior', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('image_floor_plan', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
            bases=('aircraft.basemodel',),
        ),
    ]
